version: "3.8"
services:
  gql-server:
    build: ./server
    ports:
      - "4000:4000"

  client:
    build: ./client
    ports:
      - "8080:80"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - gql-server
      - client
    profiles:
      - nginx

  kong:
    build: ./kong
    ports:
      - "80:8000"
      - "8443:8443"
    depends_on:
      - gql-server
      - client
    profiles:
      - kong
