version: "3.8"

services:
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - REVERSE_PROXY_TYPE=${REVERSE_PROXY_TYPE:-nginx}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: ${REVERSE_PROXY_TYPE:-nginx}-builder
    ports:
      - "80:80"
    depends_on:
      - graphql
    profiles:
      - nginx
      - kong

volumes:
  kong_data:
