services:
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      API_KEY: ${GRAPHQL_API_KEY}
    env_file:
      - path: .env # Change this to .env.dev or .env.prod as needed
        required: true

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - graphql
    environment:
      SERVER_NAME: ${SERVER_NAME}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      ALLOWED_HEADERS: ${ALLOWED_HEADERS}
      GRAPHQL_API_KEY: ${GRAPHQL_API_KEY}
    env_file:
      - path: .env # Change this to .env.dev or .env.prod as needed
        required: true
